function [] = plot_properties(x,y)
    %% settings for figure
    set(gca, ... 
            'XGrid', 'on', ...
            'YGrid', 'on', ...
            'GridLineStyle', '--', ...
            'LineWidth', 0.8, ...
            'GridAlpha', 0.5, ...
            'XMinorGrid', 'off' , ...
            'YMinorGrid', 'off', ...
            'MinorGridLineStyle', ':', ...
            ...
            'XTick', x(1):x(2):x(3), ...
            'YTick', y(1):y(2):y(3), ...
            ...
            'XLim', [x(1) x(3)], ...
            'YLim', [y(1) y(3)], ...
            ...
            'FontName', 'Times New Roman', ...
            'FontSize', 25, ...
            'FontAngle', 'italic')
    
    % set the axes labels' properties
    xlabel(gca, '$t$ in s', ...
            'Interpreter', 'latex', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 25)
    ylabel(gca, '$h_2$ in mm', ...
            'Interpreter', 'latex', ...
            'FontName', 'Times New Roman', ...
            'FontSize', 25)
    
    set(gcf, 'color','w')

    % Set figure properties to match an A4-sized PDF page
    set(gcf, 'PaperUnits', 'centimeters');
    set(gcf, 'PaperSize', [21, 29.7]); % A4 page size [Width, Height]
    set(gcf, 'PaperPosition', [0, 0, 21, 14]); % Use full width, reasonable height
    
    % Save as PDF with full width scaling
    print(gcf, 'my_scaled_plot.pdf', '-dpdf', '-r300');
    
end